### ISSUE TITLE
import into a single site

### ISSUE THREAD

**Issue by soderlind** [10up/MU-Migration#25]
Can I use this to import into a single site, i.e. export a subsite and then import it into a single site?

**Comment by nicholasio** [comment]
It doesn't really support this scenario, but it isn't that hard to support this (feel free to submit a PR), assuming you want to override the whole content of your single site with the content of the site you're importing. However, If you don't want to override the existing content, then you got a merge sort of problem, and you probably need a custom migration plan and scripts.

**Comment by nicholasio** [comment]
I actually started to work on this on #26, feel free to test it out.

**Comment by soderlind** [comment]
Excellent, thank you. Will test.
