### ISSUE TITLE
Consider adding `--blog_url` or `--blog_name` as an alternate to `--blog_id`

### ISSUE THREAD

**Issue by jgraup** [10up/MU-Migration#38]
One issue that I have is that my local multisite `blog_id` is out of sync with my remote multisite `blog_id`. It would be much easier to reference the site slug (which is the same in both) instead of the ID which will required an extra call.

```
blog_id="$(site_url=http://example.test/sitename/; wp site list | awk -v site_url=$site_url '{ if( $2 == site_url ) print $1; }')"; 
echo $blog_id;
```

For example:

```
$ wp mu-migration export all subsite.zip --blog_url=http://example.test/sitename/

$ wp mu-migration export all subsite.zip --blog_name=sitename
```

**Comment by nicholasio** [comment]
While I haven't tested, you could try running with wp-cli global --url parameter, then you wouldn't need to pass blog id.

`$ wp mu-migration export all subsite.zip --url=http://example.test/sitename/`
