### ISSUE TITLE
can I use it for multisite WP to other multisite wordpress migration??? 

### ISSUE THREAD

**Issue by cocodrino** [10up/MU-Migration#42]
Hi, good day, I need migrate a whole multisite wp to other server with other domain, would I use this plugin for achieve that???

other small question, I notice than there is an import command, do this create the db and tables or do I need create the db and then import the tables??? I ask because I'd prefer the second way because I think use other db name...

thank you...

**Comment by nicholasio** [comment]
If you're migrating the whole multisite as-is to another server, you don't necessarily need to use this tool. You can simply move everything (files and database) to another server and run a search-replace to update the domain.

Regarding you second question, this tool assumes you have two WordPress instances and you want to move sites between these two, so this tool won't handle creating the database or setting up WordPress, it works with existing WordPress instances.
