### ISSUE TITLE
Error: 'mu-migration' is not a registered wp command. See 'wp help' for available commands.

### ISSUE THREAD

**Issue by hendriq** [10up/MU-Migration#45]
When i try to export a subsite from a multisite network using: `wp mu-migration export all subsite.zip --blog_id=2`, it's given that error. 

I am running wp_cli in a Local/Flywheel virtual machine with SSH prompt.

Thanks in advance.

**Comment by nicholasio** [comment]
Did you follow the steps described in the README to install mu-migration? it is a wp-cli plugin and does not come with wp-cli by default.

**Comment by hendriq** [comment]
I just simply ran `wp package install 10up/mu-migration` as said in README. I ran it again just to be sure and still not working

**Comment by nicholasio** [comment]
what was the output of running that command? Does it work if you install it as a WordPress plugin? (make sure to run composer install manually)
