### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by Chuckworld** [10up/MU-Migration#46]
Trying to add MU-migration via command line, and continue to get this error. In my vagrant box I was able to allot more memory via VirtualBox. On a real life server I have limited knowledge (but sudo privileges), yet I keep running into roadblocks. The most common error:

PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 33554432 bytes) in phar:///usr/local/bin/wp/vendor/composer/composer/src/Composer/DependencyResolver/RuleSetGenerator.php on line 126

**Comment by Chuckworld** [comment]
found a solution - was using older version of RedHat and allotting more memory to php.ini along with installing helper apps enabled me to get this installed...but lets get a progress report on this MU thing!!

**Comment by nicholasio** [comment]
Hi @Chuckworld thanks for reporting this. I'll try to replicate this issue. Can you let me know which PHP version and WP-CLI you were using?

**Comment by nicholasio** [comment]
I was able to replicate the issue and it is happening to any wp-cli package. Turns out this is a common issue with wp-cli: https://make.wordpress.org/cli/handbook/common-issues/#php-fatal-error-allowed-memory-size-of-999999-bytes-exhausted-tried-to-allocate-99-bytes

I'll add a note to the README.
