### ISSUE TITLE
Child theme from site of network install not exported ?

### ISSUE THREAD

**Issue by mfaure** [10up/MU-Migration#49]
Hello,

(First of all, your package is awesome :) )

A feedback of a migration I've just made : I exported a site from a network install. When importing the zip file (as a single site install), I saw the child theme had not been imported (child theme of TwentyThirteen).

Hope this helps

**Comment by nicholasio** [comment]
Was the child theme the active theme of the site? The tool will only include the child theme (and the parent theme) if it is the active theme of the exported site.

**Comment by mfaure** [comment]
Yes the child theme was active
