### ISSUE TITLE
Travis builds exploding

### ISSUE THREAD

**Issue by azito122** [10up/MU-Migration#54]
This is an issue identified in both pull requests #50 and #53. I've tracked the failure down to the fact that `wp-cli` removed most of the command requirements from `composer.json` in versions greater than `1.5.1`. Therefore, simply requiring `wp-cli/wp-cli` results in only the commands `cli` and `help` being available.

Possible solutions:
1. Stick with `v1.5.1`
2. Manually require all needed `wp` commands, e.g. in `.travis.yml`:
```
install:
  - composer require wp-cli/wp-cli:dev-master
  - composer require wp-cli/core-command:dev-master
  - composer require wp-cli/config-command:dev-master
  - composer update
  - composer install
  - bash bin/install-package-tests.sh
```
3. Use a different method of installing `wp-cli`, like `curl`ing the `.phar` file.

**Comment by nicholasio** [comment]
@azito122 I think solution is fine 2? you open for a PR?

**Comment by azito122** [comment]
@nicholasio Working on it now
