### ISSUE TITLE
Warning: Unable to create the zip file

### ISSUE THREAD

**Issue by tiagoefreitas** [10up/MU-Migration#58]
Getting this warning and the zip file is not generated.

I change includes/commands/class-mu-migration-export.php to print the exception, get this error:

Warning: exception 'Alchemy\Zippy\Exception\InvalidArgumentException' with message 'Invalid path mu-migration-430119266ananda-events.sql' in /home/pg20619/.wp-cli/packages/vendor/10up/mu-migration/vendor/alchemy/zippy/src/Resource/Teleporter/LocalTeleporter.php:56
Stack trace:
#0 /home/pg20619/.wp-cli/packages/vendor/10up/mu-migration/vendor/alchemy/zippy/src/Resource/ResourceTeleporter.php(41): Alchemy\Zippy\Resource\Teleporter\LocalTeleporter->teleport(Object(Alchemy\Zippy\Resource\Resource), '/tmp/zippy_5bf2...')
#1 /home/pg20619/.wp-cli/packages/vendor/10up/mu-migration/vendor/alchemy/zippy/src/Resource/ResourceManager.php(67): Alchemy\Zippy\Resource\ResourceTeleporter->teleport('/tmp/zippy_5bf2...', Object(Alchemy\Zippy\Resource\Resource))
#2 /home/pg20619/.wp-cli/packages/vendor/10up/mu-migration/vendor/alchemy/zippy/src/Adapter/ZipExtensionAdapter.php(247): Alchemy\Zippy\Resource\ResourceManager->handle('/home/pg20619/p...', Array)
#3 /home/pg20619/.wp-cli/packages/vendor/10up/mu-migration/vendor/alchemy/zippy/src/Adapter/ZipExtensionAdapter.php(207): Alchemy\Zippy\Adapter\ZipExtensionAdapter->addEntries(Object(Alchemy\Zippy\Adapter\Resource\ZipArchiveResource), Array, true)
#4 /home/pg20619/.wp-cli/packages/vendor/10up/mu-migration/vendor/alchemy/zippy/src/Adapter/AbstractAdapter.php(58): Alchemy\Zippy\Adapter\ZipExtensionAdapter->doCreate('/home/pg20619/p...', Array, true)
#5 /home/pg20619/.wp-cli/packages/vendor/10up/mu-migration/includes/commands/class-mu-migration-export.php(513): Alchemy\Zippy\Adapter\AbstractAdapter->create('events.zip', Array, true)
#6 [internal function]: TenUp\MU_Migration\Commands\ExportCommand->all(Array, Array)
#7 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#8 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#9 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#10 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(365): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#11 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(388): WP_CLI\Runner->run_command(Array, Array)
#12 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1113): WP_CLI\Runner->_run_command_and_exit()
#13 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#14 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#15 phar:///home/pg20619/wp-cli/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(23): WP_CLI\bootstrap()
#16 phar:///home/pg20619/wp-cli/wp-cli.phar/php/boot-phar.php(11): include('phar:///home/pg...')
#17 /home/pg20619/wp-cli/wp-cli.phar(4): include('phar:///home/pg...')
#18 {main}Unable to create the zip file

**Comment by tiagoefreitas** [comment]
Basically for files created by MU-Migration in the local folder its not passing the whole path to zippy, only for folders.

**Comment by tiagoefreitas** [comment]
Actually the problem is MU-Migration is not creating any files to zip...
I run it likes this:

php -d suhosin.executor.include.whitelist=phar  ~/wp-cli/wp-cli.phar mu-migration export all events.zip --plugins --themes --uploads

**Comment by tiagoefreitas** [comment]
Problem was using PHP 5.6, changed to 7.1 and worked

**Comment by nicholasio** [comment]
@tiagoefreitas I don't thing we ever had a hard requirement on PHP 7 but I'll review this, I should probably update the dependencies anyway! Thanks for the report

**Comment by nicholasio** [comment]
@tiagoefreitas one of the dependencies bumped PHP requirements to 7.1, I have downgraded for now so that this tool can support PHP 5.6 as well
