### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by derekPrivate** [10up/MU-Migration#69]
Just trying this tool for the first time. I have successfully exported my multi-site Wordpress to a zip file. I have copied the zip file to a (completely) new Wordpress installation. I run the command

wp mu-migration import all site.zip --new_url=dev.xxxxxxxx.com/wordpress --path=/var/public/sites/wordpress

and get the message
Error establishing a database connection

Any ideas how I can investigate the issue? I have checked usernames etc using phpMyAdmin

**Comment by nicholasio** [comment]
Does the site work properly outside of MU-Migration? This seems to be an issue within your database connection since MU-Migration does not handle connections to the database directly.

**Comment by derekPrivate** [comment]
Yes - it is a brand-new site (clean install. wp setup) and I can connect to the server with my browser - the site just has the default content.

--
Derek Morris
derek.morris@allofmymail.com

**Comment by derekPrivate** [comment]
P.S. 

To confirm the connection, I just added this to a file and then opened with the browser and received “Connected successfully”

<?php
$link = mysqli_connect('localhost', 'root', 'root');
if (!$link) {
die('Could not connect: ' . mysqli_error());
}
echo 'Connected successfully';
mysqli_close($link);
?>

--
Derek

**Comment by derekPrivate** [comment]
OK, I eventually found the issue. I was having the same problem with wp core update and tracked it down (eventually!) to using the native php instead of the one supplied with MAMP.

Thanks for your help.
