### ISSUE TITLE
n00b issue: Unable to create archive

### ISSUE THREAD

**Issue by Sortova** [10up/MU-Migration#80]
Running into an issue trying to create my first archive.

On Ubuntu 18.04.4 LTS with php 7.2, when I run:

wp mu-migration export all single-site.zip --themes --plugins --uploads --verbose

I get

Exporting site meta data...
Exporting users...
Success: 2 users have been exported
Exporting tables
Success: The export is now complete
Zipping files....
Warning: Unable to create archive

Could be something on my end, so I was hoping there would be a way to get better debug information. I would expect it to create the archive next. 

Sorry if this question has been answered previously, but I've only found one similar reference and that user was on Windows.

**Comment by Sortova** [comment]
Hrm - must be something with that site. I ran it against another site on the same system:

Exporting site meta data...
Exporting users...
Success: 33 users have been exported
Exporting tables
Success: The export is now complete
Zipping files....
Success: A zip file named single-site.zip has been created

Note that the zip took a long time. On the other site it fails almost immediately.

**Comment by Sortova** [comment]
Final update for the evening: I have three websites I'd like to move. The migration worked for one of them. The others die pretty quickly with "unable to create archive". Looking for any kind of log message now to figure this out.

**Comment by nicholasio** [comment]
Are all of the sites on the same server? That error is most likely indicating the zip extension is missing.

**Comment by Sortova** [comment]
Yeah - all three are on the same server. Really beating my head against the wall on this, as the big, complicated site moved without much of an issue but these two smaller sites are being a pain. Seems weird it would work for one and not the others. I made sure all three sites were completely up to date with inactive plugins removed.

I assume that MU-migration doesn't really log anything? Outside of --verbose I'm not sure how to get more information as to why it is dying.

**Comment by Sortova** [comment]
One more data point: I took the smaller of the two sites and moved it to the new server as a single site. MU-migration fails with the same error, although that site is running Ubuntu 20.04 with PHP 7.4.

**Comment by Sortova** [comment]
No worries. I'll do it manually. Thanks for making one of the site moves easier.
