### ISSUE TITLE
Can't perform migration when mysql is not installed at server app ( remote mysql )

### ISSUE THREAD

**Issue by renzocastillo** [10up/MU-Migration#86]
**Describe the bug**

First of all, I would like to say that I'm not sure if this is a bug at all, because maybe I should assume that this tool uses mysql for performing db operation and it should be available at local. 

**Steps to Reproduce**

wp mu-migration import all site.zip --new_url=multisite.test/new-site --allow-root

**Expected behavior**

I expect to import all tables and have the files, plugins  and everything imported from single site into the subsite at the mulsitie. The issue is that this mulsitie has wordpress operating with two servers ( one for apps dir and the other one for database)
**Screenshots**

![image](https://user-images.githubusercontent.com/21372177/97898123-6f0b8500-1d05-11eb-9f0d-e77db3230bab.png)

**Environment information**
 - Device:  Production Cloud Server
 - OS:  Ubuntu 18.04 LTS
 - Browser and version: 
 - WordPress version:  5.5
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   `
### wp-core ###
version: 5.4.4
site_language: es_ES
user_language: es_ES
timezone: America/Lima
permalink: /%postname%/
https_status: false
user_registration: true
default_comment_status: open
multisite: true
user_count: 341
site_count: 45
network_count: 1
dotorg_communication: true

### wp-active-theme ###

name: RANDOM - Principal (wp-theme-random_principal)
version: 1.0.0
author: Staff Digital Team
author_website: https://staffdigital.pe
parent_theme: Random - Core (wp-theme-random)
theme_features: title-tag, menus, custom-logo, post-thumbnails, widgets
theme_path: /var/www/html/wp-content/themes/wp-theme-random_principal

### wp-parent-theme ###

name: random - Core (wp-theme-random)
version: 1.0.0
author: Staff Digital Team
author_website: https://staffdigital.pe
theme_path: /var/www/html/wp-content/themes/wp-theme-random

### wp-mu-plugins (2) ###

rms_unique_wp_mu_pl_fl_nm.php: author: (undefined), version: (undefined)
WP Migrate DB Compatibility: version: 1.2, author: Delicious Brains

### wp-plugins-active (28) ###

Advanced Custom Fields PRO: version: 5.8.12, author: Elliot Condon (latest version: 5.9.2)
Ajax Search Pro: version: 4.16.3, author: Ernest Marcinko (latest version: 4.19.4)
Classic Editor: version: 1.5, author: WordPress Contributors (latest version: 1.6)
Contact Form 7: version: 5.2, author: Takayuki Miyoshi (latest version: 5.3)
Contact Form 7 Conditional Fields: version: 1.9.9, author: Jules Colle (latest version: 1.9.14)
Contact Form DB: version: 2.10.34, author: Michael Simpson
Export WordPress Menus: version: 1.2, author: Tyche Softwares
Loco Translate: version: 2.4.0, author: Tim Whitlock (latest version: 2.4.4)
NS Cloner - Site Copier: version: 4.0.9, author: Never Settle
PDF Poster: version: 1.5, author: bPlugins (latest version: 1.6.3)
Redirection: version: 4.8, author: John Godley (latest version: 4.9.2)
Safe SVG: version: 1.9.9, author: Daryll Doyle
Simple Custom Post Order: version: 2.5.0, author: Colorlib (latest version: 2.5.1)
The Events Calendar: version: 5.1.5, author: Modern Tribe, Inc. (latest version: 5.2.1)
TinyMCE Advanced: version: 5.4.0, author: Andrew Ozz
True Multisite Indexer: version: 5.4.4, author: Misha Rudrastyh
random Salesforce: version: 1.2, author: Picol Estudio
User Role Editor: version: 4.55.1, author: Vladimir Garagulya (latest version: 4.56.1)
User Switching: version: 1.5.5, author: John Blackbourn & contributors (latest version: 1.5.6)
Visual Composer: version: 29.0, author: visualcomposer.com (latest version: 30.1)
Widget Options: version: 3.7.4, author: Widget Options Team (latest version: 3.7.6)
WordPress Importer: version: 0.7, author: wordpressdotorg
WordPress Multisite User Sync/Unsync: version: 1.2.0, author: Obtain Infotech
WP Activity Log: version: 4.1.2, author: WP White Security (latest version: 4.1.4)
WP Mail SMTP: version: 2.2.1, author: WPForms (latest version: 2.5.1)
WP Migrate DB: version: 1.0.14, author: Delicious Brains (latest version: 1.0.16)
Yoast Duplicate Post: version: 3.2.5, author: Enrico Battocchi & Team Yoast (latest version: 3.2.6)
Yoast SEO: version: 14.8.1, author: Team Yoast (latest version: 15.2.1)

### wp-plugins-inactive (5) ###

Logged-in-only: version: 2.1.0, author: Drivingralle
Members: version: 3.0.10, author: MemberPress (latest version: 3.1.3)
Polylang: version: 2.7.4, author: WP SYNTEX (latest version: 2.8.3)
WP-PageNavi: version: 2.93.3, author: Lester 'GaMerZ' Chan
WP User Profile Restriction: version: 1.0.4, author: Shawon

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: No disponible
imagemagick_version: No disponible
gd_version: 2.3.0
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 4.15.0-112-generic x86_64
httpd_software: Apache/2.4.29 (Ubuntu)
php_version: 7.4.9 64bit
php_sapi: apache2handler
max_input_variables: 2000
time_limit: 180
memory_limit: 9024M
max_input_time: 60
upload_max_size: 100M
php_post_max_size: 100M
curl_version: 7.58.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.7.30-0ubuntu0.18.04.1
client_version: mysqlnd 7.4.9

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 9024M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### wp_mail_smtp ###

version: 2.2.1
license_key_type: lite
debug: No se han encontrado avisos de depuración.
db_tables: udp20wp_wpmailsmtp_tasks_meta

`
</details>

`
**Additional context**

**Comment by renzocastillo** [comment]
Ok so just for the record I solved it using this command:

apt install mysql-client-core-5.7

So basically I needed to install mysql client in order to perform connection to remote mysql host and then plugin keep working smoothly

**Comment by nicholasio** [comment]
Yep - this tool does assume you have mysql client on the server from which you're running the command from.

Glad you were able to get it to work!
