### ISSUE TITLE
Migration hanging when importing users

### ISSUE THREAD

**Issue by anekola** [10up/MU-Migration#88]
**Describe your question**
I'm not sure if this is a bug or if I'm doing something wrong, because this seems rather basic. I did one site import with a few dozen users that worked fine, but now that I'm attempting one for sites with hundreds to thousands of users the import keeps hanging while "Importing Users."

On one of the larger site, it returns a few PHP errors while doing so:

```
PHP Warning: array_combine(): Both parameters should have an equal number of elements in /home/vagrant/.wp-cli/packages/vendor/10up/mu-migration/includes/commands/class-mu-migration-import.php on line 90
Warning: array_combine(): Both parameters should have an equal number of elements in /home/vagrant/.wp-cli/packages/vendor/10up/mu-migration/includes/commands/class-mu-migration-import.php on line 90
PHP Warning: array_diff_assoc(): Argument #1 is not an array in /home/vagrant/.wp-cli/packages/vendor/10up/mu-migration/includes/commands/class-mu-migration-import.php on line 118
Warning: array_diff_assoc(): Argument #1 is not an array in /home/vagrant/.wp-cli/packages/vendor/10up/mu-migration/includes/commands/class-mu-migration-import.php on line 118
```

Does this make any sense? Could someone have a clue about what is going wrong?

**Comment by anekola** [comment]
An update: I'm paying closer attention to the numbers, and it seems to be continuing, but it's just taking a VERY long time. In one hour it has processed ~ 600 users. This particular site has 1937 users. Perhaps this is a resource issue? I'm running this on local server, which is https://varyingvagrantvagrants.org.

**Comment by nicholasio** [comment]
Looks like there's something wrong going on. Can you open the .csv file inside the zip file and check if the CSV is malformed?

**Comment by anekola** [comment]
The CSV seems fine. But it has 348 columns. Would that number significantly
slow it down in your experience?

**Comment by nicholasio** [comment]
I assume the users have a lot of custom meta, so yes it should slow down as for each user the import script will have to make individual calls to update each post meta (this can probably be improved).

The warnings you're getting are definitely concerning though as they seem to indicate bugs in the logic to import users.

**Comment by anekola** [comment]
Yeah, I understand why, but the export is including custom meta that is
only needed on certain subsites that I'm not actually exporting. I
attempted to delete the columns from the CSV that I didn't need and when I
tried to import I got this message:

Error: There's something wrong with your zip package, unable to find
required files

**Comment by anekola** [comment]
Thanks @nicholasio – I was able to get into the CVS and remove columns I didn't need. That sped things up. The server still incrementally slowed down, so I occasionally needed to stop and restart the machine. Luckily, it picked up where it left off with users. 

The warnings were related to a plugin issue. I'm on WordPress VIP, and it doesn't notify me when to update mu-plugins locally :) Sorry about that!
