### ISSUE TITLE
Cannot import subsite in Windows

### ISSUE THREAD

**Issue by DominatorCode** [10up/MU-Migration#89]
When I import a subsite into a Windows system, at the stage of extracting tables, I get an error:

**Extracting zip package...
Importing tables...
Error: sed not present, please install sed**

I'm just usin this command, nothing special:
**wp mu-migration import all subsite-test.zip --blog_id=1**

Also, I found and installed this sed application https://sourceforge.net/projects/gnuwin32/files/sed/4.2.1/sed-4.2.1-setup.exe
but it's not helped for me

**Comment by nicholasio** [comment]
Unfortunately, this tool does not work inside Windows.

I suggest you try WSL.
